"""initial

Revision ID: 64524c63b666
Revises: 
Create Date: 2026-06-08 10:24:41.664877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64524c63b666'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key id'),
    sa.Column('ptype', sa.String(length=255), nullable=False, comment='Policy type: p / g'),
    sa.Column('v0', sa.String(length=255), nullable=False, comment='Role ID / User x_id'),
    sa.Column('v1', sa.TEXT(), nullable=False, comment='API path / Role name'),
    sa.Column('v2', sa.String(length=255), nullable=True, comment='Request method'),
    sa.Column('v3', sa.String(length=255), nullable=True),
    sa.Column('v4', sa.String(length=255), nullable=True),
    sa.Column('v5', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casbin_rule_id'), 'casbin_rule', ['id'], unique=False)
    op.create_table('login_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key id'),
    sa.Column('user_x_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(), nullable=False, comment='User email'),
    sa.Column('status', sa.Integer(), nullable=False, comment='Login status (0 failed, 1 success)'),
    sa.Column('ip', sa.String(), nullable=False, comment='Login IP address'),
    sa.Column('country', sa.String(), nullable=True, comment='Country'),
    sa.Column('region', sa.String(), nullable=True, comment='Region'),
    sa.Column('city', sa.String(), nullable=True, comment='City'),
    sa.Column('user_agent', sa.TEXT(), nullable=False, comment='User-Agent header'),
    sa.Column('os', sa.String(), nullable=True, comment='Operating system'),
    sa.Column('browser', sa.String(), nullable=True, comment='Browser'),
    sa.Column('device', sa.String(), nullable=True, comment='Device'),
    sa.Column('msg', sa.TEXT(), nullable=False, comment='Message'),
    sa.Column('login_time', sa.DateTime(), nullable=False, comment='Login time'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='Creation time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_log_id'), 'login_log', ['id'], unique=False)
    op.create_table('opera_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key id'),
    sa.Column('trace_id', sa.String(length=32), nullable=False, comment='Request Tracking ID'),
    sa.Column('user_email', sa.String(), nullable=True, comment='User Email'),
    sa.Column('method', sa.String(), nullable=False, comment='Request method'),
    sa.Column('title', sa.String(), nullable=False, comment='Operating module'),
    sa.Column('path', sa.String(), nullable=False, comment='Request path'),
    sa.Column('ip', sa.String(), nullable=False, comment='IP address'),
    sa.Column('country', sa.String(), nullable=True, comment='Country'),
    sa.Column('region', sa.String(), nullable=True, comment='Region'),
    sa.Column('city', sa.String(), nullable=True, comment='City'),
    sa.Column('user_agent', sa.String(), nullable=False, comment='Request header'),
    sa.Column('os', sa.String(), nullable=False, comment='Operating system'),
    sa.Column('browser', sa.String(), nullable=False, comment='Browser (software)'),
    sa.Column('device', sa.String(), nullable=False, comment='Device'),
    sa.Column('args', sa.JSON(), nullable=False, comment='Request Parameters'),
    sa.Column('status', sa.Integer(), nullable=False, comment='Operation status (0 abnormal 1 normal)'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='Operation status code'),
    sa.Column('msg', sa.TEXT(), nullable=False, comment='Alert message'),
    sa.Column('cost_time', sa.Float(), nullable=False, comment='Request elapsed time (ms)'),
    sa.Column('opera_time', sa.DateTime(), nullable=False, comment='Operating time'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='Creation time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opera_log_id'), 'opera_log', ['id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key id'),
    sa.Column('x_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='role name'),
    sa.Column('status', sa.Integer(), nullable=False, comment='Role status (0 deactivated 1 normal)'),
    sa.Column('remark', sa.Text(), nullable=True, comment='note'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='Creation time'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='update time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('x_id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key id'),
    sa.Column('x_id', sa.String(length=32), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('salt', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_multi_login', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_login_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('join_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='Creation time'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='update time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('x_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary Key ID'),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_opera_log_id'), table_name='opera_log')
    op.drop_table('opera_log')
    op.drop_index(op.f('ix_login_log_id'), table_name='login_log')
    op.drop_table('login_log')
    op.drop_index(op.f('ix_casbin_rule_id'), table_name='casbin_rule')
    op.drop_table('casbin_rule')
    # ### end Alembic commands ###
