"""shasec core models

Revision ID: 7d7d41ad0eef
Revises: 64524c63b666
Create Date: 2026-06-11 14:55:17.816721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7d41ad0eef'
down_revision: Union[str, None] = '64524c63b666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key id'),
    sa.Column('x_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable target name'),
    sa.Column('url', sa.String(length=2048), nullable=False, comment='Target URL or host'),
    sa.Column('type', sa.String(length=32), nullable=False, comment='website / api / graphql / host'),
    sa.Column('is_authorized', sa.Boolean(), nullable=False, comment='Owner authorized this target for scanning'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='Creation time'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='update time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('x_id')
    )
    op.create_index(op.f('ix_target_id'), 'target', ['id'], unique=False)
    op.create_table('scan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key id'),
    sa.Column('x_id', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='Audited target'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='pending / running / completed / failed'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True, comment='Failure reason when status=failed'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='Creation time'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='update time'),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('x_id')
    )
    op.create_index(op.f('ix_scan_id'), 'scan', ['id'], unique=False)
    op.create_index(op.f('ix_scan_target_id'), 'scan', ['target_id'], unique=False)
    op.create_table('ai_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key id'),
    sa.Column('x_id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False, comment='Analyzed scan'),
    sa.Column('score', sa.Integer(), nullable=False, comment='Security score 0-100 (higher is safer)'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Executive summary'),
    sa.Column('impacts', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True, comment='AI provider that produced this (e.g. ollama)'),
    sa.Column('raw', sa.JSON(), nullable=True, comment='Raw provider output for audit'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='Creation time'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='update time'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('x_id')
    )
    op.create_index(op.f('ix_ai_analysis_id'), 'ai_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_scan_id'), 'ai_analysis', ['scan_id'], unique=True)
    op.create_table('finding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key id'),
    sa.Column('x_id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False, comment='Owning scan'),
    sa.Column('plugin', sa.String(length=64), nullable=False, comment='Source plugin (nmap, nuclei, ...)'),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False, comment='critical / high / medium / low / info'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='Creation time'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='update time'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('x_id')
    )
    op.create_index(op.f('ix_finding_fingerprint'), 'finding', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_finding_id'), 'finding', ['id'], unique=False)
    op.create_index(op.f('ix_finding_scan_id'), 'finding', ['scan_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key id'),
    sa.Column('x_id', sa.String(length=32), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False, comment='Reported scan'),
    sa.Column('format', sa.String(length=16), nullable=False, comment='pdf / html / markdown / json'),
    sa.Column('location', sa.String(length=1024), nullable=True, comment='Storage object key / path'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='Creation time'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='update time'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('x_id')
    )
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    op.create_index(op.f('ix_report_scan_id'), 'report', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_scan_id'), table_name='report')
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_finding_scan_id'), table_name='finding')
    op.drop_index(op.f('ix_finding_id'), table_name='finding')
    op.drop_index(op.f('ix_finding_fingerprint'), table_name='finding')
    op.drop_table('finding')
    op.drop_index(op.f('ix_ai_analysis_scan_id'), table_name='ai_analysis')
    op.drop_index(op.f('ix_ai_analysis_id'), table_name='ai_analysis')
    op.drop_table('ai_analysis')
    op.drop_index(op.f('ix_scan_target_id'), table_name='scan')
    op.drop_index(op.f('ix_scan_id'), table_name='scan')
    op.drop_table('scan')
    op.drop_index(op.f('ix_target_id'), table_name='target')
    op.drop_table('target')
    # ### end Alembic commands ###
